spring:
  liquibase:
    enabled: true
    change-log: classpath*:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  h2:
    console:
      enabled: true